const PRODUCTSURL = "https://dijins-products-api.vercel.app/products"

const STORE_PRODUCTS = "STORE_PRODUCTS"
const SET_PRODUCTS_LOADING = "SET_PRODUCTS_LOADING"
const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR"

const STORE_PRODUCT_DETAILS = "STORE_PRODUCT_DETAILS"
const SET_PRODUCT_DETAILS_LOADING = "SET_PRODUCT_DETAILS_LOADING"
const SET_PRODUCT_DETAILS_ERROR = "SET_PRODUCT_DETAILS_ERROR"

const SET_PRODUCTS_ON_FILTER = "SET_PRODUCTS_ON_FILTER"
const SWITCH_VIEW = "SWITCH_VIEW"

const UPDATE_SORT = "UPDATE_SORT"
const SORT_PRODUCTS = "SORT_PRODUCTS"

export {PRODUCTSURL,
    STORE_PRODUCTS,
    SET_PRODUCTS_LOADING,
    SET_PRODUCTS_ERROR,
    STORE_PRODUCT_DETAILS,
    SET_PRODUCT_DETAILS_LOADING,
    SET_PRODUCT_DETAILS_ERROR,
    SET_PRODUCTS_ON_FILTER,
    SWITCH_VIEW,
    UPDATE_SORT,
    SORT_PRODUCTS
}