const PRODUCTSURL = "https://dijins-products-api.vercel.app/products"

const STORE_PRODUCTS = "STORE_PRODUCTS"
const SET_PRODUCTS_LOADING = "SET_PRODUCTS_LOADING"
const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR"

const STORE_PRODUCT_DETAILS = "STORE_PRODUCT_DETAILS"
const SET_PRODUCT_DETAILS_LOADING = "SET_PRODUCT_DETAILS_LOADING"
const SET_PRODUCT_DETAILS_ERROR = "SET_PRODUCT_DETAILS_ERROR"

const SET_PRODUCTS_ON_FILTER = "SET_PRODUCTS_ON_FILTER"
const SWITCH_VIEW = "SWITCH_VIEW"

const UPDATE_SORT = "UPDATE_SORT"
const SORT_PRODUCTS = "SORT_PRODUCTS"
const UPDATE_FILTERS = "UPDATE_FILTERS"
const FILTER_PRODUCTS = "FILTER_PRODUCTS"
const RESET_FILTERS = "RESET_FILTERS"
const ADD_TO_CART = "ADD_TO_CART"


const TOGGLE_ITEM_AMOUNT = "TOGGLE_ITEM_AMOUNT"
const REMOVE_ITEM = "REMOVE_ITEM"
const CLEAR_CART = "CLEAR_CART"
const CALCULATE_TOTAL = "CALCULATE_TOTAL"


export {PRODUCTSURL,
    STORE_PRODUCTS,
    SET_PRODUCTS_LOADING,
    SET_PRODUCTS_ERROR,
    STORE_PRODUCT_DETAILS,
    SET_PRODUCT_DETAILS_LOADING,
    SET_PRODUCT_DETAILS_ERROR,
    SET_PRODUCTS_ON_FILTER,
    SWITCH_VIEW,
    UPDATE_SORT,
    SORT_PRODUCTS,
    UPDATE_FILTERS,
    FILTER_PRODUCTS,
    RESET_FILTERS,
    ADD_TO_CART,
    TOGGLE_ITEM_AMOUNT,
    REMOVE_ITEM,
    CLEAR_CART,
    CALCULATE_TOTAL
}