const PRODUCTSURL = "https://dijins-products-api.vercel.app/products"

const STORE_PRODUCTS = "STORE_PRODUCTS"
const SET_PRODUCTS_LOADING = "SET_PRODUCTS_LOADING"
const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR"

const STORE_PRODUCT_DETAILS = "STORE_PRODUCT_DETAILS"
const SET_PRODUCT_DETAILS_LOADING = "SET_PRODUCT_DETAILS_LOADING"
const SET_PRODUCT_DETAILS_ERROR = "SET_PRODUCT_DETAILS_ERROR"



export {PRODUCTSURL,
    STORE_PRODUCTS,
    SET_PRODUCTS_LOADING,
    SET_PRODUCTS_ERROR,
    STORE_PRODUCT_DETAILS,
    SET_PRODUCT_DETAILS_LOADING,
    SET_PRODUCT_DETAILS_ERROR
}